# Generated by Django 5.2.7 on 2025-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timezone_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='response_file_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='revision_file_url',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
