# Generated by Django 5.2.7 on 2025-11-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage_core_chatme_is_read_40c122_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatme_task_id_3c96d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatme_is_read_40c122_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_user_id_1cc5b6_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='response_file_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='revision_file_url',
        ),
        migrations.AddField(
            model_name='task',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Awaiting Review', 'Awaiting Review'), ('Revision Requested', 'Revision Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='core_task_task_id_db0f96_idx'),
        ),
    ]
