# Generated by Django 5.2.7 on 2025-11-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_taskcategory_options_alter_timezone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AddField(
            model_name='task',
            name='timezone_str',
            field=models.CharField(blank=True, help_text='Fallback for frontend string input', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='client_uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='admin_responses/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='revision_file',
            field=models.FileField(blank=True, null=True, upload_to='revisions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='flag',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
