# Generated by Django 5.2.7 on 2025-11-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_taskcategory_options_task_timezone_str_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_status_e18e62_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_client__05877a_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_deadlin_aa9504_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_task_id_db0f96_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Review', 'Awaiting Review'), ('Revision Requested', 'Revision Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='timezone_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_proposals', to='core.task'),
        ),
    ]
