# Generated by Django 5.2.7 on 2025-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_budget_source',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('admin', 'Admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='negotiation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending_admin_review', 'Pending Admin Review'), ('pending_student_response', 'Pending Student Response'), ('pending_admin_response', 'Pending Admin Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=30),
        ),
    ]
