# Generated by Django 5.2.7 on 2025-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_accepted_budget_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted_budget_source',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('admin', 'Admin')], help_text='Who made the offer that was finally accepted?', max_length=10, null=True),
        ),
    ]
