# Generated by Django 5.2.7 on 2025-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_rejected_at_alter_task_accepted_budget_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='withdrawal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_created', 'New Task Created'), ('task_accepted', 'Task Accepted'), ('task_completed', 'Task Completed'), ('message_received', 'New Message'), ('budget_proposed', 'Budget Proposed'), ('revision_requested', 'Revision Requested'), ('deadline_approaching', 'Deadline Approaching'), ('system', 'System Notification'), ('budget_accepted', 'Budget Accepted'), ('budget_countered', 'Budget Countered'), ('budget_rejected', 'Budget Rejected'), ('task_withdrawn', 'Task Withdrawn')], default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted_budget_source',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
